project:
  type: website
  output-dir: docs

website:
  bread-crumbs: true
  title: "WP6: Flanders case study"
  navbar:
    search: true
    logo: images/assets/B3_logomark.png
    left:
      - text: 'Home'
        href: index.qmd
      - text: 'General indicators'
        menu:
         - text: Generate example Cube 
           href: src/preprocessing_general_indicators.qmd
         - text: Results Angiospermae 1km
           href: src/b3gbi_indicators_1km.qmd
         - text: Results Angiospermae 10km
           href: src/b3gbi_indicators_10km.qmd
         - text: Results Insecta 1km
           href: src/b3gbi_indicators_Insecta_1km.qmd
         - text: Results Insecta 10km
           href: src/b3gbi_indicators_Insecta_10km.qmd
         - text: Results Insecta 1 km (no filters)
           href: src/b3gbi_indicators_Insecta_1km_ALL.qmd
      - text: 'Phylogenetic indicators'
        menu:
         - text: Results at 1 km resolution
           href: src/pd_indicator_1km.qmd
         - text: Results at 5 km resolution
           href: src/pd_indicator_5km.qmd

      - text: 'IAS indicators'
        menu:
         - text: Target 6 indicator
           href: src/b3alien_target6.qmd
         - text: Alien Species Portal
           href: src/alienspeciesportal.qmd
      - text: 'Natura2000'
        menu:
         - text: Angiospermae 1km
           href: src/b3gbi_indicators_Natura2000.qmd
         - text: Insecta 1km 
           href: src/b3gbi_indicators_Insecta_Natura2000.qmd

           
    right: 
      - icon: github
        href: https://github.com/b-cubed-eu/WP6_use_case_Flanders
        aria-label: "GitHub Repository"
        

      

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    

editor: visual

