---
title: "Download and prepare data"
author: "Jasmijn Hillaert, Ward Langeraert"
date: "`r Sys.Date()`"
output:
  html_document:
    code_folding: show
    toc: true
    toc_float: true
    toc_collapsed: true
editor_options: 
  chunk_output_type: console
---

```{r, warning=FALSE, message=FALSE}
# Load packages
library(tidyverse) # Data wrangling and visualisation
library(here)      # Relative paths
library(sf)        # Work with spatial data
library(rgbif)
# Source
source(here("_preprocessing/R/create_cube/download_occ_cube.R"))

data_path <- here("_preprocessing","data", "raw")
```

# Goal

Load and save structured data

# Structured data

## Occurrence data

The zip file is stored under *./data/raw*.

> GBIF.org (15 April 2025) GBIF Occurrence Download <https://doi.org/10.15468/dl.ddzhrc>

```{r}

query_HD_periode1 <- "SELECT
  species,
  speciesKey,
  \"year\",
  GBIF_EEARGCode(
      10000,
      decimalLatitude,
      decimalLongitude,
      COALESCE(coordinateUncertaintyInMeters,10000)
  ) AS eeacellcode,
  MIN(COALESCE(coordinateUncertaintyInMeters, 10000)) AS minCoordinateUncertaintyInMeters,
  MIN(GBIF_TEMPORALUNCERTAINTY(eventDate, eventTime)) AS minTemporalUncertainty,
  COUNT(*) AS occurrences

FROM occurrence

WHERE
  occurrence.countryCode = 'BE'
  AND \"year\" >= 2001
  AND \"year\" <= 2006
  AND occurrenceStatus = 'PRESENT'
  AND (coordinateUncertaintyInMeters <= 10000 OR coordinateUncertaintyInMeters IS NULL)
  AND occurrence.basisOfRecord NOT IN ('FOSSIL_SPECIMEN', 'LIVING_SPECIMEN')
  AND NOT ARRAY_CONTAINS(issue, 'ZERO_COORDINATE')
  AND NOT ARRAY_CONTAINS(issue, 'COORDINATE_OUT_OF_RANGE')
  AND NOT ARRAY_CONTAINS(issue, 'COORDINATE_INVALID')
  AND NOT ARRAY_CONTAINS(issue, 'COUNTRY_COORDINATE_MISMATCH')
  AND speciesKey IS NOT NULL
  AND decimalLatitude IS NOT NULL
  AND decimalLongitude IS NOT NULL
  AND occurrence.hasGeospatialIssues = FALSE
  AND NOT GBIF_STRINGARRAYCONTAINS(issue, 'TAXON_MATCH_FUZZY', TRUE)
  AND occurrence.speciesKey IN (2412623, 2426612, 4562143, 2432582, 5739539,
    4409131, 2368185, 5959617, 2438704, 2432359,
    2294287, 2427573, 2421365, 2421402, 2675719,
    1429194, 5323092, 5743122, 2864775, 2433753,
    2688247, 5218878, 2367936, 5218911, 2432427,
    7261875, 2432452, 2432439, 2432470, 2432416,
    9754263, 2432389, 5218522, 5218524, 2430567,
    5218471, 5218465, 5218507, 5739437, 2469188,
    1864161, 2426789, 2426805, 2432655, 7595433,
    2668958, 5051901, 2431885, 4567182, 4567215,
    2432564)
  

GROUP BY
  species,
  speciesKey,
  \"year\",
  GBIF_EEARGCode(
      10000,
      decimalLatitude,
      decimalLongitude,
      COALESCE(coordinateUncertaintyInMeters,10000)
  )
"



data_HD_periode1 <- download_occ_cube(
  sql_query = query_HD_periode1,
  file = "HD_data_2001_2006.csv",
  path = data_path,
  overwrite = TRUE
  )

```

```{r}

query_HD_periode2 <- "SELECT
  species,
  speciesKey,
  \"year\",
  GBIF_EEARGCode(
      10000,
      decimalLatitude,
      decimalLongitude,
      COALESCE(coordinateUncertaintyInMeters,10000)
  ) AS eeacellcode,
  MIN(COALESCE(coordinateUncertaintyInMeters, 10000)) AS minCoordinateUncertaintyInMeters,
  MIN(GBIF_TEMPORALUNCERTAINTY(eventDate, eventTime)) AS minTemporalUncertainty,
  COUNT(*) AS occurrences

FROM occurrence

WHERE
  occurrence.countryCode = 'BE'
  AND \"year\" >= 2007
  AND \"year\" <= 2012
  AND occurrenceStatus = 'PRESENT'
  AND (coordinateUncertaintyInMeters <= 10000 OR coordinateUncertaintyInMeters IS NULL)
  AND occurrence.basisOfRecord NOT IN ('FOSSIL_SPECIMEN', 'LIVING_SPECIMEN')
  AND NOT ARRAY_CONTAINS(issue, 'ZERO_COORDINATE')
  AND NOT ARRAY_CONTAINS(issue, 'COORDINATE_OUT_OF_RANGE')
  AND NOT ARRAY_CONTAINS(issue, 'COORDINATE_INVALID')
  AND NOT ARRAY_CONTAINS(issue, 'COUNTRY_COORDINATE_MISMATCH')
  AND speciesKey IS NOT NULL
  AND decimalLatitude IS NOT NULL
  AND decimalLongitude IS NOT NULL
  AND occurrence.hasGeospatialIssues = FALSE
  AND NOT GBIF_STRINGARRAYCONTAINS(issue, 'TAXON_MATCH_FUZZY', TRUE)
  AND occurrence.speciesKey IN (2412623, 2426612, 4562143, 2432582, 5739539,
    4409131, 2368185, 5959617, 2438704, 2432359,
    2294287, 2427573, 2421365, 2421402, 2675719,
    1429194, 5323092, 5743122, 2864775, 2433753,
    2688247, 5218878, 2367936, 5218911, 2432427,
    7261875, 2432452, 2432439, 2432470, 2432416,
    9754263, 2432389, 5218522, 5218524, 2430567,
    5218471, 5218465, 5218507, 5739437, 2469188,
    1864161, 2426789, 2426805, 2432655, 7595433,
    2668958, 5051901, 2431885, 4567182, 4567215,
    2432564)
  

GROUP BY
  species,
  speciesKey,
  \"year\",
  GBIF_EEARGCode(
      10000,
      decimalLatitude,
      decimalLongitude,
      COALESCE(coordinateUncertaintyInMeters,10000)
  )
"



data_HD_periode2 <- download_occ_cube(
  sql_query = query_HD_periode2,
  file = "HD_data_2007_2012.csv",
  path = data_path,
  overwrite = TRUE
  )

```

```{r}

query_HD_periode3 <- "SELECT
  species,
  speciesKey,
  \"year\",
  GBIF_EEARGCode(
      10000,
      decimalLatitude,
      decimalLongitude,
      COALESCE(coordinateUncertaintyInMeters,10000)
  ) AS eeacellcode,
  MIN(COALESCE(coordinateUncertaintyInMeters, 10000)) AS minCoordinateUncertaintyInMeters,
  MIN(GBIF_TEMPORALUNCERTAINTY(eventDate, eventTime)) AS minTemporalUncertainty,
  COUNT(*) AS occurrences

FROM occurrence

WHERE
  occurrence.countryCode = 'BE'
  AND \"year\" >= 2013
  AND \"year\" <= 2018
  AND occurrenceStatus = 'PRESENT'
  AND (coordinateUncertaintyInMeters <= 10000 OR coordinateUncertaintyInMeters IS NULL)
  AND occurrence.basisOfRecord NOT IN ('FOSSIL_SPECIMEN', 'LIVING_SPECIMEN')
  AND NOT ARRAY_CONTAINS(issue, 'ZERO_COORDINATE')
  AND NOT ARRAY_CONTAINS(issue, 'COORDINATE_OUT_OF_RANGE')
  AND NOT ARRAY_CONTAINS(issue, 'COORDINATE_INVALID')
  AND NOT ARRAY_CONTAINS(issue, 'COUNTRY_COORDINATE_MISMATCH')
  AND speciesKey IS NOT NULL
  AND decimalLatitude IS NOT NULL
  AND decimalLongitude IS NOT NULL
  AND occurrence.hasGeospatialIssues = FALSE
  AND NOT GBIF_STRINGARRAYCONTAINS(issue, 'TAXON_MATCH_FUZZY', TRUE)
  AND occurrence.speciesKey IN (2412623, 2426612, 4562143, 2432582, 5739539,
    4409131, 2368185, 5959617, 2438704, 2432359,
    2294287, 2427573, 2421365, 2421402, 2675719,
    1429194, 5323092, 5743122, 2864775, 2433753,
    2688247, 5218878, 2367936, 5218911, 2432427,
    7261875, 2432452, 2432439, 2432470, 2432416,
    9754263, 2432389, 5218522, 5218524, 2430567,
    5218471, 5218465, 5218507, 5739437, 2469188,
    1864161, 2426789, 2426805, 2432655, 7595433,
    2668958, 5051901, 2431885, 4567182, 4567215,
    2432564)
  

GROUP BY
  species,
  speciesKey,
  \"year\",
  GBIF_EEARGCode(
      10000,
      decimalLatitude,
      decimalLongitude,
      COALESCE(coordinateUncertaintyInMeters,10000)
  )
"



data_HD_periode3 <- download_occ_cube(
  sql_query = query_HD_periode3,
  file = "HD_data_2013_2018.csv",
  path = data_path,
  overwrite = TRUE
  )

```

```{r}
#analysing surface per EEA gridcell

#read in EEA 10 km gridcells

#CELLCODE

EEA_10km <- read_sf('./_preprocessing/data/raw/spatial/EEA_10km_Flanders_union.geojson')

test <- leaflet()%>%
  addTiles()%>%
  addPolygons(data=EEA_10km)

data_species <- st_read("C:/Users/jasmijn_hillaert/Downloads/art17_2013_2018_public.gpkg", layer = "Art17_species_distribution_2013_2018_MS")

data_species_BE_1001 <- data_species%>%
  filter(country=="BE")%>%
  filter(speciescode=="1014")

b <- st_transform(data_species_BE_1001, crs=4326)

b <- st_make_valid(b)

test <- leaflet()%>%
  addTiles()%>%
  addPolygons(data=EEA_10km)%>%
  addPolygons(data=b, color='red')

Flanders <- read_sf('./_preprocessing/data/raw/spatial/flanders_wgs84.geojson')

data_species_BE_100 <- st_intersection(b, Flanders)



test <- leaflet()%>%
  addTiles()%>%
  addPolygons(data=EEA_10km)%>%
  addPolygons(data=data_species_BE_100, color='red')
```
