
```{r, warning=FALSE, message=FALSE}
# Load packages
library(tidyverse) # Data wrangling and visualisation
library(here)      # Relative paths
library(sf)        # Work with spatial data
library(rgbif)
# Source
source(here("_preprocessing/R/create_cube/download_occ_cube.R"))

data_path <- here("_preprocessing","data", "raw")
```

# Goal

Load and save structured data

# Structured data

## Occurrence data

The zip file is stored under *./data/raw*.

> GBIF.org (15 April 2025) GBIF Occurrence Download <https://doi.org/10.15468/dl.ddzhrc>

```{r}
query_ang_1km <- "SELECT
  kingdom,
  kingdomkey,
  phylum,
  phylumkey,
  class,
  classkey,
  \"order\",
  orderkey,
  family,
  familykey,
  genus,
  genuskey,
  species,
  specieskey,
  \"year\",
  v_verbatimCoordinates,

  COUNT(*) AS occurrences

FROM occurrence

WHERE
  
  \"year\" >= 1975
  AND occurrenceStatus = 'PRESENT'
  AND datasetKey IN ('271c444f-f8d8-4986-b748-e7367755c0c1')



GROUP BY
  kingdom, kingdomkey,
  phylum, phylumkey,
  class, classkey,
  \"order\", orderkey,
  family, familykey,
  genus, genuskey,
  species, specieskey,
  \"year\",
  v_verbatimCoordinates
"


data_total_1km <- download_occ_cube(
  sql_query = query_ang_1km,
  file = "Indicator_Florabank.csv",
  path = data_path,
  overwrite = TRUE
  )

```