```{r}
#load libraries

library(sf)
library(dplyr)
library(leaflet)
library(lwgeom)
library(ggplot2)
```

```{r}
#load in Flanders shape
Flanders <- read_sf('./_preprocessing/data/raw/spatial/flanders_wgs84.geojson')
Flanders_unified <- chull(Flanders)

Flanders_map <- leaflet()%>%
  addTiles()%>%
  addPolygons(data=Flanders)

#Verwijder Brussel en andere gaten in Vlaanderen
remove_holes_sf <- function(x){
  geom <- st_geometry(x)
  new_geom <- lapply(geom, function(g){

    if (inherits(g, "POLYGON")) {
      # Alleen buitenring behouden
      st_polygon(list(g[[1]]))

    } else if (inherits(g, "MULTIPOLYGON")) {
      # Voor elk onderdeel enkel de buitenring behouden
      parts <- lapply(g, function(p) list(p[[1]]))
      st_multipolygon(parts)

    } else {
      g  # andere types onveranderd
    }
  })

  st_geometry(x) <- st_sfc(new_geom, crs = st_crs(x))
  x
}

Flanders_noholes <- remove_holes_sf(Flanders)

Flanders_map <- leaflet()%>%
  addTiles()%>%
  addPolygons(data=Flanders_noholes)

# Voeg een buffer toe van 15 km rond Vlaanderen
## 2. Projecteren naar metrisch CRS (meters)
Flanders_m <- st_transform(Flanders_noholes, 31370)

## 3. Buffer van 15 km (15,000 meter)
Flanders_buffer15km <- st_buffer(Flanders_m, dist = 15000)

## 4. Terug naar WGS84 indien gewenst
Flanders_buffer15km_wgs84 <- st_transform(Flanders_buffer15km, 4326)

Flanders_map <- leaflet()%>%
  addTiles()%>%
  addPolygons(data=Flanders_buffer15km_wgs84)

st_write(Flanders_noholes, './_preprocessing/data/raw/spatial/flanders_noholes.geojson')

st_write(Flanders_buffer15km_wgs84, './_preprocessing/data/raw/spatial/flanders_buffer15_wgs84.geojson')

f <- st_read('./_preprocessing/data/raw/spatial/flanders_buffer15_wgs84.geojson')

f <- st_convex_hull(f)
f <- st_convex_hull(f)
f <- st_convex_hull(f)
st_crs(f)

f <- st_transform(f, 4326) # will do nothing if already EPSG:4326

# 4. make geometries valid
f <- st_make_valid(f)

map <- leaflet()%>%
  addTiles()%>%
  addPolygons(data=f)
# 5. union all features into a single geometry (one polygon/multipolygon)
geom_union <- st_union(st_geometry(f))

# 6. cast to MULTIPOLYGON if necessary (safer for complex ranges)
geom_union <- st_cast(geom_union, "MULTIPOLYGON")

# 7. get WKT text
wkt <- st_as_text(geom_union)
wkt <- gsub("\n", " ", wkt)   # remove newlines if any
wkt

# Export to a file
writeLines(wkt, "./_preprocessing/data/raw/spatial/flanders_buffer15km_wkt.txt")


```

```{r}
#laad EEA grids 1km
EEA_overzicht_1km <- read_sf('./_preprocessing/data/raw/spatial/be_1km.shp')

EEA_overzicht_1km <- st_transform(EEA_overzicht_1km, crs=4326)

EEA_Flanders_union_1km <- st_intersection(EEA_overzicht_1km, Flanders_noholes)

EEA_Flanders_union_map_1km <- leaflet()%>%
  addTiles()%>%
  addPolygons(data=EEA_Flanders_union_1km)

st_write(EEA_Flanders_union_1km, './_preprocessing/data/raw/spatial/EEA_1km_Flanders_union.geojson')

```

```{r}
#laad EEA grids 10 km
EEA_overzicht_10km <- read_sf('./_preprocessing/data/raw/spatial/be_10km.shp')

EEA_overzicht_10km <- st_transform(EEA_overzicht_10km, crs=4326)

EEA_Flanders_10_km <- st_intersection(EEA_overzicht_10km, Flanders)

EEA_Flanders_union_10km <- st_intersection(EEA_overzicht_10km, Flanders_noholes)

EEA_Flanders_union_map_10km <- leaflet()%>%
  addTiles()%>%
  addPolygons(data=EEA_Flanders_10_km)

st_write(EEA_Flanders_union_10km, './_preprocessing/data/raw/spatial/EEA_10km_Flanders_union.geojson')

st_write(EEA_Flanders_10_km, './_preprocessing/data/raw/spatial/EEA_10km_Flanders_hole.geojson')

```

```{r}
Flanders_noholes <- read_sf('./_preprocessing/data/raw/spatial/flanders_noholes.geojson')

EEA_overzicht_5km <- read_sf('./_preprocessing/data/raw/spatial/EEA-Reference-Grid-5km.gpkg')

EEA_overzicht_5km <- st_transform(EEA_overzicht_5km, crs=4326)

EEA_Flanders_union_5km <- st_intersection(EEA_overzicht_5km, Flanders_noholes)

EEA_Flanders_union_map_5km <- leaflet()%>%
  addTiles()%>%
  addPolygons(data=EEA_Flanders_union_5km)

st_write(EEA_Flanders_union_5km, './_preprocessing/data/raw/spatial/EEA_5km_Flanders_union.geojson')
```
```{r}
#Add visualisation
Flanders_noholes <- st_read('./_preprocessing/data/raw/spatial/flanders_noholes.geojson')

Flanders_buffer <-st_read('./_preprocessing/data/raw/spatial/flanders_buffer15_wgs84.geojson')

Flanders_10km <- st_read('./_preprocessing/data/raw/spatial/EEA_10km_Flanders_union.geojson')

Flanders_1km <- st_read('./_preprocessing/data/raw/spatial/EEA_1km_Flanders_union.geojson')

Natura_2000 <- st_read('./_preprocessing/data/raw/spatial/EEA_1km_Natura2000.geojson')

nonNatura_2000 <- st_read('./_preprocessing/data/raw/spatial/EEA_1km_nonNatura2000.geojson')

ggplot() +
  geom_sf(data = Flanders_buffer,
          fill = "#6CDDB4",   # B-Cubed groen
          color = "#6CDDB4") +
  geom_sf(data = Flanders_noholes,
          fill = "#005957",   # B-Cubed lichtgroen
          color = "#005957") +
  theme_void()

ggplot() +
  geom_sf(data = Flanders_buffer,
          fill = "#6CDDB4",   # B-Cubed groen
          color = "#6CDDB4") +
  geom_sf(data = Flanders_noholes,
          fill = "#005957",   # B-Cubed lichtgroen
          color = "#005957") +
  geom_sf(data=Flanders_1km,
          color = '#EFF8F5',
          fill=NA)+
  theme_void()

ggplot() +
  geom_sf(
    data = nonNatura_2000,
    aes(fill = "non Natura 2000"),
    color = "#6CDDB4"
  ) +
  geom_sf(
    data = Natura_2000,
    aes(fill = "Natura 2000"),
    color = "#005957"
  ) +
  scale_fill_manual(
    name = NULL,
    values = c(
      "non Natura 2000" = "#6CDDB4",
      "Natura 2000" = "#005957"
    )
  ) +
  theme_void()

fl <- ggplot() +
  geom_sf(data = Flanders_noholes,
          fill = "#48A529",
          color = "#48A529"
) +
  theme_void()

ggsave(
  filename = "./_preprocessing/data/raw/spatial/Flanders_map.png",
  plot = fl,
  width = 8,
  height = 6,
  units = "in",
  dpi = 300
)
```

```{r}
library(leaflet)

library(sf)

hbtrl <- st_read(
  "C:/Users/jasmijn_hillaert/Downloads/ps_hbtrl/processed/ps_hbtrl/ps_hbtrl.lb72.gpkg"
)

vgtrl <- st_read(
"C:/Users/jasmijn_hillaert/Downloads/ps_vglrl/ps_vglrl.shp")

hbtrl_wgs84 <- st_transform(hbtrl, 4326)
vgtrl_wgs84 <- st_transform(vgtrl, 4326)
test <- leaflet()%>%
  addTiles()%>%
  addPolygons(data=hbtrl_wgs84, color= 'red')%>%
  addPolygons(data=vgtrl_wgs84, color= 'blue')%>%
  addPolygons(data=Natura_2000)


```


