---
title: "Download and prepare Angiosperm data"
author: "Jasmijn Hillaert, Ward Langeraert"
date: "`r Sys.Date()`"
output:
  html_document:
    code_folding: show
    toc: true
    toc_float: true
    toc_collapsed: true
editor_options: 
  chunk_output_type: console
---

```{r, warning=FALSE, message=FALSE}
# Load packages
library(tidyverse) # Data wrangling and visualisation
library(here)      # Relative paths
library(sf)        # Work with spatial data

# Source
source(here("_preprocessing/R/create_cube/download_occ_cube.R"))

data_path <- here("_preprocessing","data", "raw")
```

# Goal

Load and save structured data

# Structured data

## Occurrence data

```{r}
# nolint start: line_length_linter.
query_IAS_target6 <-  "SELECT
kingdom,
kingdomkey,
phylum,
phylumkey,
class,
classkey,
\"order\",
orderkey,
family,
familykey,
genus,
genuskey,
species,
specieskey,
PRINTF('%04d-%02d', \"year\", \"month\") yearmonth,
GBIF_EQDGCODE(2, decimallatitude, decimallongitude, 0.0) eqdcellcode,
IF(ISNULL(kingdomkey), NULL, SUM(COUNT(*)) OVER (
PARTITION BY kingdomkey, GBIF_EQDGCODE(2, decimallatitude, decimallongitude, 0.0), PRINTF('%04d-%02d', \"year\", \"month\"))) kingdomcount,
IF(ISNULL(phylumkey), NULL, SUM(COUNT(*)) OVER (
PARTITION BY phylumkey, GBIF_EQDGCODE(2, decimallatitude, decimallongitude, 0.0), PRINTF('%04d-%02d', \"year\", \"month\"))) phylumcount,
IF(ISNULL(classkey), NULL, SUM(COUNT(*)) OVER (
PARTITION BY classkey, GBIF_EQDGCODE(2, decimallatitude, decimallongitude, 0.0), PRINTF('%04d-%02d', \"year\", \"month\"))) classcount,
IF(ISNULL(familykey), NULL, SUM(COUNT(*)) OVER (
PARTITION BY familykey, GBIF_EQDGCODE(2, decimallatitude, decimallongitude, 0.0), PRINTF('%04d-%02d', \"year\", \"month\"))) familycount,
IF(ISNULL(genuskey), NULL, SUM(COUNT(*)) OVER (
PARTITION BY genuskey, GBIF_EQDGCODE(2, decimallatitude, decimallongitude, 0.0), PRINTF('%04d-%02d', \"year\", \"month\"))) genuscount,
IF(ISNULL(orderkey), NULL, SUM(COUNT(*)) OVER (
PARTITION BY orderkey, GBIF_EQDGCODE(2, decimallatitude, decimallongitude, 0.0), PRINTF('%04d-%02d', \"year\", \"month\"))) ordercount,
COUNT(DISTINCT recordedby) distinctobservers,
COUNT(*) occurrences
FROM
occurrence
WHERE
occurrence.countrycode = 'BE'
AND (occurrence.level0gid = 'BEL' OR occurrence.level1gid = 'BEL' OR occurrence.level2gid = 'BEL' OR occurrence.level3gid = 'BEL')
AND occurrence.occurrencestatus = 'PRESENT'
AND occurrence.hasgeospatialissues = FALSE
AND NOT GBIF_STRINGARRAYCONTAINS(occurrence.issue, 'TAXON_MATCH_FUZZY', TRUE)
AND (occurrence.distancefromcentroidinmeters >= 2000.0 OR occurrence.distancefromcentroidinmeters IS NULL)
AND (occurrence.specieskey IS NOT NULL AND occurrence.\"year\" IS NOT NULL AND occurrence.\"month\" IS NOT NULL AND occurrence.hascoordinate = TRUE)
GROUP BY
occurrence.kingdom,
occurrence.kingdomkey,
occurrence.phylum,
occurrence.phylumkey,
occurrence.class,
occurrence.classkey,
occurrence.\"order\",
occurrence.orderkey,
occurrence.family,
occurrence.familykey,
occurrence.genus,
occurrence.genuskey,
occurrence.species,
occurrence.specieskey,
PRINTF('%04d-%02d', occurrence.\"year\", occurrence.\"month\"),
GBIF_EQDGCODE(2, occurrence.decimallatitude, occurrence.decimallongitude, 0.0)
"

# nolint end

data_IAS_target6 <- download_occ_cube(
  sql_query = query_IAS_target6,
  file = "IAS_target6.csv",
  path = data_path,
  overwrite = TRUE
)

```

We get a big dataframe with all occurrences.

```{r}
# Explore dataframe
glimpse(data_IAS_target6)
```


```{r}
write.csv(data_IAS_target6,
          '_preprocessing/data/raw/data_IAS_target6.csv')
```
