---
title: "Download and prepare data"
author: "Jasmijn Hillaert, Ward Langeraert"
date: "`r Sys.Date()`"
output:
  html_document:
    code_folding: show
    toc: true
    toc_float: true
    toc_collapsed: true
editor_options: 
  chunk_output_type: console
---

```{r, warning=FALSE, message=FALSE}
# Load packages
library(tidyverse) # Data wrangling and visualisation
library(here)      # Relative paths
library(sf)        # Work with spatial data
library(rgbif)
# Source
source(here("_preprocessing/R/create_cube/download_occ_cube.R"))

data_path <- here("_preprocessing","data", "raw")
```

# Goal

Load and save structured data

# Structured data

## Occurrence data

The zip file is stored under *./data/raw*.

> GBIF.org (15 April 2025) GBIF Occurrence Download <https://doi.org/10.15468/dl.ddzhrc>

```{r}
query_HD_periode1 <- "SELECT
  species,
  speciesKey,
  \"year\",
  GBIF_EuroStatCode(
      10000,
      decimalLatitude,
      decimalLongitude,
      COALESCE(coordinateUncertaintyInMeters,10000)
  ) AS eeacellcode,
  MIN(COALESCE(coordinateUncertaintyInMeters, 10000)) AS minCoordinateUncertaintyInMeters,
  MIN(GBIF_TEMPORALUNCERTAINTY(eventDate, eventTime)) AS minTemporalUncertainty,
  COUNT(*) AS occurrences

FROM occurrence

WHERE
  occurrence.countryCode = 'BE'
  AND \"year\" BETWEEN 2002 AND 2006
  AND occurrenceStatus = 'PRESENT'
  AND (coordinateUncertaintyInMeters <= 10000 OR coordinateUncertaintyInMeters IS NULL)
  AND NOT occurrence.basisOfRecord IN ('FOSSIL_SPECIMEN', 'LIVING_SPECIMEN')
  AND NOT ARRAY_CONTAINS(issue, 'ZERO_COORDINATE')
  AND NOT ARRAY_CONTAINS(issue, 'COORDINATE_OUT_OF_RANGE')
  AND NOT ARRAY_CONTAINS(issue, 'COORDINATE_INVALID')
  AND NOT ARRAY_CONTAINS(issue, 'COUNTRY_COORDINATE_MISMATCH')
  AND speciesKey IS NOT NULL
  AND decimalLatitude IS NOT NULL
  AND decimalLongitude IS NOT NULL
  AND occurrence.hasGeospatialIssues = FALSE
  AND NOT GBIF_STRINGARRAYCONTAINS(issue, 'TAXON_MATCH_FUZZY', TRUE)
  AND (
    occurrence.speciesKey IN ( ...lijst... )
    OR occurrence.acceptedSpeciesKey IN ( ...lijst... )
  )

GROUP BY
  species,
  speciesKey,
  \"year\",
  GBIF_EuroStatCode(
      10000,
      decimalLatitude,
      decimalLongitude,
      COALESCE(coordinateUncertaintyInMeters,10000)
  )
"


data_HD_periode1 <- download_occ_cube(
  sql_query = ,
  file = "HD_data_2002_2006.csv",
  path = data_path,
  overwrite = TRUE
  )

```

We get a big dataframe with all occurrences.

```{r}
# Explore dataframe
glimpse(data_total_1km)
```

```{r}
#read in native species in Flanders (Waarnemingen)

be_plants_native <-  read.csv('_preprocessing/data/interim/Waarnemingen_native_species.csv')
# alternative cube waarbij enkel native soorten op observed plantlijst
# Natuurpunt worden behouden
cube_native <- data_total_1km[data_total_1km$specieskey %in%
                              be_plants_native$acceptedUsageKey,]

#add filter for temporal uncertainty
cube_native <- cube_native%>%
  filter(mintemporaluncertainty <= 315360000)

```

# Select Flanders grid cells

```{r}
FLANDERS_EEA_1km <- st_read('./_preprocessing/data/raw/spatial/EEA_1km_Flanders_union.geojson')
FLANDERS_EEA_1km_Natura2000 <- st_read('./_preprocessing/data/raw/spatial/EEA_1km_Natura2000.geojson')
FLANDERS_EEA_1km_nonNatura2000 <- st_read('./_preprocessing/data/raw/spatial/EEA_1km_nonNatura2000.geojson')
```

```{r}
Cube_Angio_Flanders <- cube_native%>%
  filter(eeacellcode %in% FLANDERS_EEA_1km$CELLCODE)
Cube_Angio_Flanders_Natura2000 <- cube_native%>%
  filter(eeacellcode %in% FLANDERS_EEA_1km_Natura2000$CELLCODE)
Cube_Angio_Flanders_nonNatura2000 <- cube_native%>%
  filter(eeacellcode %in% FLANDERS_EEA_1km_nonNatura2000$CELLCODE)
```

```{r}
write.csv(Cube_Angio_Flanders,
          '_preprocessing/data/raw/Angiosperm_data_Flanders_1km.csv')
write.csv(Cube_Angio_Flanders_Natura2000,
          '_preprocessing/data/raw/Angiosperm_data_Flanders_Natura2000.csv')
write.csv(Cube_Angio_Flanders_nonNatura2000,
          '_preprocessing/data/raw/Angiosperm_data_Flanders_nonNatura2000.csv')
```
