## Indicator type

State indicator.

## Explanation

Observed species richness represents the total number of unique species discovered and recorded. For maps, the value is calculated for each spatial cell. For time-series analyses, the value is calculated per time step over the complete data cube. 

- High value: A high number of unique species, indicating a diverse local community.

- Low value: A low number of unique species, signalling a species-poor habitat.

## Applicability for policy

This metric is necessary for determining biodiversity hotspots on a map or tracing potential declines in species richness over time. With taxonomic filtering, one can quantify the number of species in a particular cohort, such as known alien species, tree species, or carnivores.

## Limitations

Observed species richness is highly sensitive to sampling bias and human observation effort. If certain grid cells are studied more carefully or visited more frequently by volunteers than others, they will artificially appear to have more species. Therefore, this metric should be interpreted within the context of a measure of survey effort, such as total occurrences or occurrence density. Furthermore, results are skewed by species detectability. Rare or widely dispersed species are easily missed by citizens, whereas highly conspicuous or easy-to-find species will often be reported (Hillebrand et al. 2018).
