## Indicator type

Data quality indicator.

## Explanation

The total number of occurrences is calculated by summing the occurrences of all species observed for each cell or year. For maps, the value is calculated for each spatial cell. For time-series analyses, the value is calculated per time step over the complete data cube.

- High value: A high number of occurrences has been submitted, signalling a hotspot for human outdoor activity or nature reporting.
- Low value: Relatively few occurrence records have been submitted, potentially indicating data "blind spots" where few people pass by and report observations. These ‘blind spots’ are also not part of long-term monitoring programs.

## Applicability for policy

This metric indicates the degree and locations of citizen science engagement. It also helps to interpret other metrics more correctly by highlighting biases in survey effort over time and space. While not itself an indicator, it is vital for interpreting the results of calculated indicators.

## Limitations

It indicates which locations are preferred for outdoor recreation and nature recording, rather than which locations are of conservation value. Though you will tend to get lower numbers of observations in an area with fewer species.
