---
title: "Calculate General Indicators Flanders Case Study WP6"
output: html_document
---

#install packages

```{r}
#install.packages("b3gbi", repos = c("https://b-cubed-eu.r-universe.dev", "https://cloud.r-project.org"))
#install.packages("rnaturalearthdata")
#install.packages("sf")
#install.packages("taxize")
#install.packages("here")


gc()
library(b3gbi)
library(sf)
library(taxize)
library(here)
```

#Define input file and directory of output files

```{r}
Focus <- 'Florabank_data_Flanders_5km'
Focus_1km <- 'Florabank_data_Flanders_1km'
Focus_B <- 'Angiosperm_data_Flanders_5km'

#filter only data of Florabank before 2023!
data <- read.csv(paste0('./_preprocessing/data/raw/', Focus, '.csv'))
data_1km <- read.csv(paste0('./_preprocessing/data/raw/', Focus_1km, '.csv'))
data_B <- read.csv(paste0('./_preprocessing/data/raw/', Focus_B, '.csv'))


Angiosperm_data_cube_1km <- process_cube(read.csv(paste0('./_preprocessing/data/raw/', Focus_1km, '.csv')), first_year= 2000 , last_year=2022)


Angiosperm_data_cube_5km <- process_cube(read.csv(paste0('./_preprocessing/data/raw/', Focus, '.csv')), first_year=2000, last_year=2022)

Angiosperm_data_cube_B <- process_cube(read.csv(paste0('./_preprocessing/data/raw/', Focus_B, '.csv')),last_year=2022)

Angiosperm_data_cube_B_ts <- process_cube(read.csv(paste0('./_preprocessing/data/raw/', Focus_B, '.csv')),first_year = 2000, last_year=2022)

```

#Running b3gbi indicators ##8.1. Observed Species Richness \~ recorded richness

```{r}
'Observed richness is calculated by summing the number of unique species observed for each year or each cell. Observed richness is highly dependent on the comprehensiveness of the dataset it is being applied to. If some regions are more intensively, carefully or systematically sampled than others, this will likely reflect as higher observed richness. Observed richness also depends on the relative abundance and spatial aggregation of each species, with less abundant and less aggregated species less likely to be discovered during surveys (Hillebrand et al., 2018), as well as the detectability of each species.'

OSR_map <- obs_richness_map(Angiosperm_data_cube_1km,
                            cell_size="grid")

OSR_ts <- obs_richness_ts(Angiosperm_data_cube_1km, 
                          cell_size="grid")

a <-plot_ts(OSR_ts)

OSR_ts <- as.data.frame(OSR_ts$data)

ggplot(data = OSR_map$data) +
  geom_sf(aes(fill = diversity_val), color = NA) +
  scale_fill_viridis_c(na.value = NA) +
  theme_minimal()+
  theme(legend.title = element_blank())

library(ggplot2)

b <- ggplot(OSR_ts, aes(x = year, y = diversity_val)) +
  geom_point() +
  geom_smooth(method = "loess", se = FALSE) +
  scale_y_continuous(limits = c(0, NA)) +
  theme_minimal() +
  labs(x = "Year", y = "Native angiosperm species richness")


```


 
 https://www.gbif.org/occurrence/download/0051797-260226173443078
 GBIF Occurrence Download https://doi.org/10.15468/dl.r7kjgc Accessed from R via rgbif (https://github.com/ropensci/rgbif) on 2026-03-20
 https://www.gbif.org/occurrence/download/0043784-2602261734430787
 GBIF Occurrence Download https://doi.org/10.15468/dl.y9hpfa Accessed from R via rgbif (https://github.com/ropensci/rgbif) on 2026-03-17
 
 

